routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/testMail', 'frontend\PageController@testmail');
Route::get('/', 'frontend\PageController@index')->middleware('auth');
Route::get('/order/{type}', 'frontend\OrderController@index',function($type){})->middleware('auth');
Route::post('/order/confirmTransacrion', 'frontend\OrderController@confirm')->middleware('auth');
Route::post('/order/{type}', 'frontend\OrderController@store',function($type){})->middleware('auth');

Route::get('/profile', 'frontend\ProfileController@index')->middleware('auth');
Route::post('/profile/update', 'frontend\ProfileController@update')->middleware('auth');
Route::post('/profile/changePassword', 'frontend\ProfileController@changePassword')->middleware('auth');
Route::post('/profile/kycUpload', 'frontend\ProfileController@uploadKYC')->middleware('auth');

Route::get('/your-referrals', 'frontend\ReferralController@index')->middleware('auth');

Route::get('/my-wallet', 'frontend\WalletController@index')->middleware('auth');
Route::post('/setWallet', 'frontend\WalletController@setWallet')->middleware('auth');

Route::get('/setting', 'frontend\SettingController@index')->middleware('auth');
Route::get('/2fa/enable', 'frontend\Google2FAController@enableTwoFactor');
Route::get('/2fa/validate', 'frontend\Google2FAController@getValidateToken');

Route::get('/2fa/testValidate', 'frontend\Google2FAController@test2FAToken');
Route::post('/2fa/getTFAData', 'frontend\Google2FAController@getTFAToken');
Route::post('/2fa/validate', ['middleware' => 'throttle:5', 'uses' => 'frontend\Google2FAController@postValidateToken']);
Route::post('/2fa/disable', 'frontend\Google2FAController@disableTwoFactor');

Route::prefix('api')->group(function() {
    Route::post('/checkUserEmail', 'API\AjaxController@checkUserEmail');
});

Route::prefix('api')->group(function() {
    Route::post('/chkExistingEmail', 'API\AjaxController@chkExistingEmail');
});

Route::prefix('cmscontrol')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'backend\AdminController@index')->name('admin.dashboard')->middleware('auth:admin');
    Route::get('/transactionData/{id}', 'backend\AdminController@viewTransactionData',function($id){})->name('admin.transaction.data')->middleware('auth:admin');
    Route::post('/accept/order/{id}', 'backend\AdminController@acceptOrder')->middleware('auth:admin');
    Route::get('/order/reject/{id}', 'backend\AdminController@rejectOrder',function($id){})->name('admin.transaction.reject')->middleware('auth:admin');
    
    Route::get('/kyc','backend\AdminController@viewKyc')->middleware('auth:admin');
    Route::get('/kyc/approve/{id}','backend\AdminController@approveKyc',function($id){})->middleware('auth:admin');
    Route::get('/kyc/reject/{id}','backend\AdminController@rejectKyc',function($id){})->middleware('auth:admin');
});

Route::get('/member/login', 'Auth\UserLoginController@showLoginForm')->name('login');
Route::post('/member/login', 'Auth\UserLoginController@login')->name('member.login.submit');
Route::get('/member/register',['use'=>'member.register',function(){
    return view('auth.register');
}]);
Route::get('/verify/{email}/{code}', 'Auth\ActivateUserController@index',function($email,$code){});

Route::post('/member/register', 'Auth\RegisterController@register');
Route::get('/member/verify_regis', 'Auth\RegisterController@verify_regis');
Route::get('/member/logout', 'Auth\UserLoginController@logout');


Route::get('/password/reset/', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname', 'code', 'email', 'password', 'verify_code', 'verify'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public static $kycStatus = [
        0=>['style'=>"text-warning",'msg'=>'Pending'],
        1=>['style'=>"text-success",'msg'=>'Approved'],
        99=>['style'=>"text-danger",'msg'=>'Rejected']
    ];

    public function getKycStatusDisplay($html=0){
        $message = self::$kycStatus[$this->kyc_status]['msg'];
        if($html==1){
            return "<p class='".self::$kycStatus[$this->kyc_status]['style']."'>".$message."</p>";
        }else{
            return $message;
        }
    }

    public function referring()
    {
    return $this->belongsToMany('App\Models\User', 'user_referrer', 'user_id', 'referrer_id')->withPivot('status')
    ->withTimestamps();
    }

    // Same table, self referencing, but change the key order
    public function referrer()
    {
    return $this->belongsToMany('App\Models\User', 'user_referrer', 'referrer_id', 'user_id')->withPivot('status')
    ->withTimestamps();
    }


    public function getUsernameAttribute(){
        return $this->name.' '.$this->surname;
    }

    public function transaction()
    {
        return $this->hasMany('App\Models\Transaction');
    }

    public function commission()
    {
        return $this->hasMany('App\Models\Commission');
    }

    public function country()
    {
    return $this->belongsTo('App\Models\Country');
    }
}

app/Http/Controllers/backend/AdminController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

use App\Models\Transaction;
use App\Models\User;

class AdminController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth:admin');
    }
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.admin');
    }

    public function viewTransactionData($id){
        $transaction = Transaction::find($id);
        return view('backend.transaction_detail',compact('transaction'));
    }

    public function acceptOrder(Request $request,$id){
        if($id == $request->id){
            $transaction = Transaction::where('id',$request->id)->where('status',0)->with('wallet')->with('user')->first();
            if($transaction){
                if($transaction->status == 0){
                    if($request->send_type == 1){
                        $send_amount = $transaction->send_value;      
                    }else if($request->send_type == 2){
                        $send_amount = $request->actually_coin;
                    }
                    

                    $fic_amount = bcmul($send_amount,$transaction->fic_rate,8);
                    $fic_bonus = number_format(($fic_amount * $transaction->bonus_rate)/100, 8,'.','');
                    $all = bcadd($fic_amount,$fic_bonus,8);
                    $fic_all = bcadd($fic_amount,$fic_bonus,8);
                    
                    $transaction->actual_send = number_format($send_amount,8,'.','');
                    $transaction->actual_fic = number_format($fic_amount,8,'.','');
                    $transaction->actual_bonus = number_format($fic_bonus,8,'.','');
                    $transaction->actual_fic_recieve = number_format($fic_all,8,'.','');
                    $transaction->status = 1;
                    $transaction->save();
                
                    $userFIC = $transaction->user->fic;
                    $transaction->user->fic = number_format(($userFIC+$fic_all),8,'.',''); 
                    $transaction->user->save();

                    if($transaction->commission){
                        if($transaction->user->referring[0]->pivot->status == 0){
                            $transaction->commission->fic = number_format(($fic_amount * 3.5)/100, 8,'.','');
                            $transaction->commission->status = 1;
                            $transaction->commission->save();
                            
                            $userCommission = $transaction->commission->user->fic; 
                            $transaction->commission->user->fic = number_format(($userCommission+$transaction->commission->fic),8,'.','');
                            $transaction->commission->user->save();
                            
                            $transaction->user->referring[0]->pivot->status = 0;
                            $transaction->user->referring[0]->pivot->save();
                        }
                    }
                }
                return redirect('/cmscontrol');
            }else{
                return back();
            }
        }else{
            return back();
        }
    }

    public function rejectOrder($id){
        if($id != ''){
            $order = Transaction::find($id);
            if($order){
                $order->status = 99;
                $order->save();
            }
        }
        return back();
    }


    public function viewKyc(){
        //return "Test viewKyc";
        return view('backend.kyc-list');
    }
    public function approveKyc($id){
        $user = User::where('code',$id)->first();
        if($user){
            $user->kyc_status = 1;
            $user->save();
        }

        return back();
    }
    public function rejectKyc($id){
        $user = User::where('code',$id)->first();
        if($user){
            $user->kyc_status = 99;
            $user->save();
        }

        return back();
    }
}

resources/views/backend/admin.blade.php
@extends('layouts.default')
@section('content')
<div class="row">
    <div class="col-md-6 col-sm-12 col-xs-12" style="margin-left: 1em; margin-top: 1em; color: #000; font-weight: bold; font-size: 1.5em; padding-left: 5px;">Flora FIC Admin Control Panel</div>
    <div class="col-md-12 col-sm-12 col-xs-12" style="margin-bottom: 2em; background-color: white;">
        <div class="col-md-12" style="margin-top: 1em; margin-bottom: 1em; color: #000; font-size: 1em;">
            <div class="row">
                <div class="col-md-12 mt-3 mb-3 pt-3 pb-3" style="font-size: 1.2em; background-color: #0099cc; color: #ffffff;"> <strong>FIC Balance : </strong> {{number_format(App\Models\User::whereNotNull('fic')->sum('fic'),8,'.',',')}} FIC</div>    
                <div class="col-md-12"><hr></div>
            </div>
        </div>

        <div class="col-md-12 col-sm-12 col-xs-12" style="margin-bottom: 2em; background-color: white;">
        @php($transaction = App\Models\Transaction::whereNotNull('transfer_code')->where('status','!=',99)->orderBy('created_at','desc')->get())
        @if($transaction->isNotEmpty())
        @php($i = 1)
            <div class="col-md-12 mt-3" style="margin-top: 1em; margin-bottom: 1em; color: #000; font-size: 12px; padding: 0px;">
                <table id="example" class="table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Date</th>
                            <th scope="col">Type</th>
                            <th scope="col">Send</th>
                            <th scope="col">FIC Recive</th>
                            <th scope="col">FIC Bonus</th>
                            <th scope="col">KYC Status</th>
                            <th scope="col">Status</th>
                            <th colspan="2" scope="col" class="text-center">Opt</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Date</th>
                            <th scope="col">Type</th>
                            <th scope="col">Send</th>
                            <th scope="col">FIC Recive</th>
                            <th scope="col">FIC Bonus</th>
                            <th scope="col">KYC Status</th>
                            <th scope="col">Status</th>
                            <th colspan="2" scope="col" class="text-center">Opt</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach($transaction as $key => $data)
                            @include('backend.partials._transaction_list', ['data'=>$data,'order'=>$i])
                            @php($i++)
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif
        </div>
        <hr/>
        <div class="col-md-12 col-sm-12 col-xs-12" style="margin-bottom: 2em; background-color: white;">
        Waiting Buyer comfirm the transaction id
        @php($waitingTransaction = App\Models\Transaction::whereNull('transfer_code')->where('status','!=',99)->orderBy('created_at','desc')->get())
        @if($waitingTransaction->isNotEmpty())
        @php($i = 1)
            <div class="col-md-12 mt-3" style="margin-top: 1em; margin-bottom: 1em; color: #000; font-size: 12px; padding: 0px;">
                <table id="example" class="table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Date</th>
                            <th scope="col">Send To Address</th>
                            <th scope="col">Transaction ID</th>
                            <th scope="col">Type</th>
                            <th scope="col">Send</th>
                            <th scope="col">FIC Recive</th>
                            <th scope="col">FIC Bonus</th>
                            <th scope="col">KYC Status</th>
                            <th scope="col">Status</th>
                            <th colspan="2" scope="col" class="text-center">Opt</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Date</th>
                            <th scope="col">Send To Address</th>
                            <th scope="col">Transaction ID</th>
                            <th scope="col">Type</th>
                            <th scope="col">Send</th>
                            <th scope="col">FIC Recive</th>
                            <th scope="col">FIC Bonus</th>
                            <th scope="col">KYC Status</th>
                            <th scope="col">Status</th>
                            <th colspan="2" scope="col" class="text-center">Opt</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach($waitingTransaction as $key => $data)
                            @include('backend.partials._transaction_waiting_list', ['data'=>$data,'order'=>$i])
                            @php($i++)
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif
        </div>                
    </div>        
</div>  


@endsection
@section('style')
<link href="{{asset('css/index-custom.css')}}" rel="stylesheet" type="text/css">
@endsection
@section('script')
<script>
    $('a[data-toggle="tooltip"]').tooltip({
        animated: 'fade'
    });
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>
@endsection

resources/views/backend/kyc-list.blade.php
@extends('layouts.default')
@section('content')
@php($users = App\Models\User::whereNotNull('kyc_file')->orderBy('kyc_status')->orderBy('created_at','desc')->with('country')->get())
<div class="row">
    <div class="col-md-6 col-sm-12 col-xs-12" style="margin-left: 1em; margin-top: 1em; color: #000; font-weight: bold; font-size: 1.5em; padding-left: 5px;">Flora FIC Admin Control Panel
    </div>

    <div class="col-md-12 col-sm-12 col-xs-12" style="margin-bottom: 2em; background-color: white;">
        <div class="col-md-12" style="margin-top: 1em; margin-bottom: 1em; color: #000; font-size: 1em;">
            <div class="row">
                <div class="col-md-12 mt-3 mb-3 pt-3 pb-3" style="font-size: 1.2em; background-color: #0099cc; color: #ffffff;"> <strong>KNOW YOUR CUSTOMER</strong> </div>    
                <div class="col-md-12"><hr></div>
            </div>
        </div>
        @if($users->isNotEmpty())
        <div class="col-md-12 col-sm-12 col-xs-12" style="margin-bottom: 2em; background-color: white;">
            <div class="col-md-12 mt-3" style="margin-top: 1em; margin-bottom: 1em; color: #000; font-size: 12px; padding: 0px;">
                <table id="example" class="col-md-12 table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Name</th>
                            <th scope="col">Surname</th>
                            <th scope="col">Country</th>
                            <td scope="col">email</td>
                            <th scope="col">kyc</th>
                            <th scope="col">Status</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $key => $value)
                        <tr>
                            <td>{{$key+=1}}</td>
                            <td>{{$value->name}}</td>
                            <td>{{$value->surname}}</td>
                            <td>{{($value->country)?$value->country->name:'-'}}</td>
                            <td>{{$value->email}}</td>
                            <td align="center">
                                @if(File::extension(asset('images/kyc/'.$value->kyc_file)) == 'pdf')
                                    <a href="{{asset('images/kyc/'.$value->kyc_file)}}" target="_blank">
                                        <img src="{{asset('images/pdf_icon.svg')}}" width="50px">
                                        <p>View PDF</p>
                                    </a>
                                @else
                                    <img src="{{asset('images/kyc/'.$value->kyc_file)}}" width="100px">
                                @endif
                            </td>
                            <td>
                                @if($value->kyc_status != 0)
                                {!!$value->getKycStatusDisplay(1)!!}
                                @else
                                <a href="{{url('/cmscontrol/kyc/approve/'.$value->code)}}">
                                    <button class="btn btn-sm btn-success">Approve</button>
                                </a>
                                <a href="{{url('/cmscontrol/kyc/reject/'.$value->code)}}">
                                    <button class="btn btn-sm btn-danger"><i class="fa fa-times-circle"></i></button>
                                </a>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th scope="col">No.</th>
                            <th scoonpe="col">Name</th>
                            <th scope="col">Surname</th>
                            <th scope="col">Country</th>
                            <td scope="col">email</td>
                            <th scope="col">kyc</th>
                            <th scope="col">Status</th>                            
                        </tr>
                    </tfoot>
                    
                </table>
            </div>
        </div>
        @endif
    </div>
    <hr/>
        
</div>

@endsection
@section('style')
<link href="{{asset('css/index-custom.css')}}" rel="stylesheet" type="text/css">
@endsection
@section('script')
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>
@endsection

resources/views/backend/transaction_detail.blade.php
@extends('layouts.default')
@section('content')
<div class="row">
    <div class="col-md-6" style="margin-left: 1em; margin-top: 1em; color: #000; font-weight: bold; font-size: 1.5em; padding-left: 5px;">Calculate your investment amount</div>
</div>  
<form name="approveOrderFIC" id="approveOrderFIC" action="{{url('/cmscontrol/accept/order/'.$transaction->id)}}" method="POST">
    <div class="row">
    <div class="col-12 col-md-11 div-white mb-5">
        <!-- Example Bar Chart Card-->
        <div class="col-12 col-md-12" style="margin-top: 1em; margin-bottom: 1em; color: #000;">
        Transaction Order Buy FIC coins with {{$transaction->wallet->code}}
        </div>
        <div class="row text-center left-em-3">
          <div class="col-md-1"></div>
          <div class="col-md-4 select-buy-currency">
              <img src="{{asset('images/'.$transaction->wallet->logo)}}" style="margin-top: 1.5em;">
              <!-- <img src="img/buy-with-eos.png" style="margin-top: 1.5em;"> -->
              <div class="top-em1">{{$transaction->wallet->code}}</div>
              <!-- <div class="top-em1">EOS</div> -->
          </div>
          <div class="col-md-2 arrow-convert align-center d-xl-block d-none d-md-block">
              <img src="{{asset('images/arrow-convert.png')}}" class="mt-4">
              <!-- <img src="img/arrow-convert.png" class="mt-4"> -->
          </div>
          <!-- show extra small -->
          <div class="d-xl-none d-sm-none d-md-none col-12 mg-left4">
              <div class="arrow-convert">
                <img src="{{asset('images/arrow-convert-down.png')}}">
                <!-- <img src="img/arrow-convert-down.png"> -->
              </div>
          </div>
          <div class="col-md-4 select-buy-currency">
              <img src="{{asset('images/fic-currency.png')}}" class="mt-4" style="width: 140px;height: 140px;">
              <!-- <img src="img/fic-currency.png" style="width: 140px;height: 140px;" class="mt-4"> -->
              <div class="top-em1">FIC</div>
          </div>
          <div class="col-md-1"></div>
        </div>


    <!-- ******************** -->
    <div class="row left-em-3 mt-4">
        <div class="col-md-1"></div>
        <div class="col-12 col-md-4" style="padding: 0px;">
            <h6 class="ex-left">Buyer send:</h6>
                <div class="col-md-12">
                  <div class="input-group">
                      <div id="sender_box" class="input-group-prepend">
                        <input type="radio" name="send_type" value="1" checked="checked">&nbsp;
                        {{$transaction->send_value}}
                        <!-- 10.00000000 --> &nbsp;&nbsp;
                        <span class="" style="padding-left: 1px; padding-right: 1px; border-top-right-radius: 5px; border-bottom-right-radius: 5px;">{{$transaction->wallet->code}} <!-- <stong>EOS</stong> --></span>
                      </div>
                  </div>
                </div>
            <h6 class="ex-left mgtop">Actual recieve:</h6> 
              <div class="col-md-12">
                <div class="input-group"> 
                    <div id="actually_box" class="input-group-prepend">
                      <input type="radio" name="send_type" value="2" class="mt-2">&nbsp;
                      <input type="number" name="actually_coin" class="form-control" id="actually_coin" data-per-fic="{{$transaction->bonus_rate}}" value="0.00000000">
                      <span class="input-group-text" style="padding-left: 1px; padding-right: 1px; border-top-right-radius: 5px; border-bottom-right-radius: 5px;"> {{$transaction->wallet->code}} </span>
                    </div>
                </div>
              </div>
            <h6 class="ex-left mt-2">bonuses:</h6>
            <div class="input-group ex-left text-danger">
                {{$transaction->bonus_rate}} <!-- 15 -->
            </div>
        </div>
        <div class="col-md-2 arrow-convert align-center"></div>
        <div class="col-12 col-md-4" style="padding: 0px;">
            <h6 class="ex-left">Buyer receive:</h6>
            <div class="col-md-12">
              <div class="input-group">
                <div class="input-group-prepend">
                  <input type="number" name="fic_receive" class="form-control" id="fic_receive" value="{{$transaction->fic_receive}}">
                  <span class="input-group-text" style="padding-left: 1px; padding-right: 1px; border-top-right-radius: 5px; border-bottom-right-radius: 5px;">FIC</span>
                </div>
              </div>
            </div>
            <h6 class="ex-left mt-2">Including bonuses:</h6>
            <div class="col-md-12">
              <div class="input-group">
                <div class="input-group-prepend">
                  <input type="number" name="all_fic_receive" class="form-control" id="all_fic_receive" value="{{$transaction->all_fic_receive}}">
                  <div class="input-group-text" style="padding-left: 1px; padding-right: 1px; border-top-right-radius: 5px; border-bottom-right-radius: 5px;">FIC</div>
                </div>
              </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-bottom: 1em;"></div>
    <div class="col-2 col-md-2"></div>
    <div class="col-10 col-md-10">
        <h4>Transaction Imformation</h4>
        <table>
            <tr>
                <td>Buyer Name</td>
                <td>{{$transaction->user->username}}/td>
            </tr>
            <tr>
                <td>Buyer Email</td>
                <td>{{$transaction->user->email}}</td>
            </tr>
            <tr>
                <td>Order Date</td>
                <td>{{$transaction->created_at->format('d-m-Y H:i:s')}}</td>
            </tr>
            <tr>
                <td>Transaction ID</td>
                <td>{{$transaction->transfer_code}}</td>
            </tr>
            <tr>
                <td>To Wallet</td>
                <td>{{$transaction->to_wallet}}</td>
            </tr>
            <tr>
                <td>Buyer ETH Wallet</td>
                <td>{{$transaction->user->eth_wallet}}</td>
            </tr>
        </table>
    </div>
    <div class="row" style="margin-top: 2em;margin-bottom: 1em;">
        <div class="col-md-12 text-center">
            <br>
            <input type="hidden" name="id" value="{{$transaction->id}}">
            <button type="button" id="submit_order" class="btn btn-warning btn-lg" style="color: #fff;">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i> &nbsp;&nbsp;&nbsp;Approve Order
            </button>
            <button type="button" id="back" class="btn btn-danger btn-lg" style="color: #fff;" onclick="window.history.go(-1); return false;">
            <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> &nbsp;&nbsp;&nbsp;Back
            </button>
        </div>
        <div class="col-md-5"></div>
    </div>
</div>
{{ csrf_field() }}
</form>
@endsection
@section('script')
<script src="{{asset('js/jquery.plugin.js')}}"></script>
<script src="{{asset('js/jquery.maxlength.js')}}"></script>
<script>
    $(document).ready(function() {
        $('#submit_order').click(function(){
            //alert($('input[name="send_type"]:checked').val());
            //alert($('input[name="actually_coin"]').val());
            if($('input[name="send_type"]:checked').val() == 2 && $('input[name="actually_coin"]').val() == false){
                alert('Error');
            }else{
                $('#approveOrderFIC').submit();
            }
        });
        $('input[name="send_type"]').change(function(){
            if($(this).val() == 2){
                $('#actually_box').removeAttr('disabled');
                $('#sender_box').attr('disabled',true);
            }else{
                $('#sender_box').removeAttr('disabled');
                $('#actually_box').attr('disabled',true);
            }
        });
        $('#actually_coin').change(function(){
            //alert($(this).val());
        })
    });
</script>
@endsection